dist: trusty
sudo: false

env:
  - distribution: solaris
    version: "10"
    minor: "11"

before_install:
  # Install the latest version of Packer with ansible
  - sudo apt-get install -y software-properties-common
  - sudo apt-add-repository -y ppa:ansible/ansible && sudo apt-get update && sudo apt-get install -y ansible
  - sudo apt-get update && sudo apt-get install -y ansible
  - sudo ansible-galaxy install git+https://github.com/diodonfrost/ansible-role-packer
  - sudo ansible-pull -U https://github.com/diodonfrost/ansible-role-packer tests/test.yml

before_script:
  - packer --version

script:
  # Validate packer templates files
  - packer validate ${distribution}-${version}/${version}.${minor}.json
